baseURL = "https://liridonbejta2.netlify.com"
languageCode = "en-us"
title = "Eddie Webb"
theme = "hugo-resume"

[params]
    firstName = "Liridon"
    lastName = "Bejta"
    address = "Tilburg, Noord-Brabant"
    #phone = "1-555-555-1234"
    contactNote = "Data Scientist"
    profileImage = "img/Liri.jpg"
    email = "liridonbejta@live.nl"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/liridon-bejta-34637b119/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/lbejta/"

#[[params.handles]]
    #name = "Bitbucket"
    #link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/9228703/liri"
    icon = "stack-overflow"

#[[params.handles]]
    #name = "Keybase"
    #link = "https://keybase.io/edwardawebb"
    #icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
