---
title: About
author: Liridon Bejta
slug: about
categories: []
tags: []
comments: false
showMeta: false
clearReading: false
---
I see myself as a business developer who uses advanced techniques to solve problems rather than a data scientist. The process of turning raw data into insights, and communicating those insights in order to inspire people to make data-driven decisions is what interests me the most. Being able to translate real world problems into a problem which can be solved with data, and communicating those results back to the business is what I'm trying to get better at every single day. 

Learning new things keeps me going. Therefore, I dedicated this blog to show you the things I learned, created, or stumpled upon. I will try to post every now and then. All of my creations can be found in the **Projects** map. 

Furthermore, I love to read (mostly non-fiction) books (hit me up for any good suggestions!). I always carry a book when I'm on the road. Other things that interests me are sports and nutrition and behavioral economics. 

Want to get in touch? Or do you have any suggestions? You can always [**E-mail**](mailto:liridonbejta@live.nl) me or connect via the LinkedIn button below!   